2018-01-23 00:18:16.760755: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Epoch 0
# of batches 9
[0.5506587, 798.0, 7311.0, 52.0, 6565.0]
Epoch 1
# of batches 9
[0.71791387, 4855.0, 5717.0, 1646.0, 2508.0]
Epoch 2
# of batches 9
[0.73353255, 6148.0, 4654.0, 2709.0, 1215.0]
Epoch 3
# of batches 9
[0.78561729, 5121.0, 6448.0, 915.0, 2242.0]
Epoch 4
# of batches 9
[0.79879123, 4959.0, 6804.0, 559.0, 2404.0]
Epoch 5
# of batches 9
[0.82826293, 5336.0, 6861.0, 502.0, 2027.0]
Epoch 6
# of batches 9
[0.85270947, 5687.0, 6870.0, 493.0, 1676.0]
Epoch 7
# of batches 9
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    model.train()
  File "/home/memcadem/Documents/Projects/de-identifier/model.py", line 88, in train
    sess.run(self.train_step, feed_dict={self.x: batch_x, self.y: batch_y})
  File "/home/memcadem/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/memcadem/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/memcadem/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/memcadem/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/memcadem/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
KeyboardInterrupt
